notifications:
  email: false
language: go
go:
- 1.11.x
install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- go get -u github.com/gobuffalo/packr/packr
script:
- make test
before_deploy:
- make dist
deploy:
  provider: releases
  api_key:
    secure: PNdace/6EZAnI93l4dkhb1re/BSKucZmJf7jlapvc6saVmU5VIS+ZHBk1UTiCvvcz0NxweR52lxKCBtdhOBEFVeMLr4iEuGDxTk8omVIts7L9ntkt+q2YeOGV3sK8LvrmbxcV+tLW/DGv8blc0zCMAbNTjMN3CT21C/+qe1ObfUfIhInXaB7rK9wqWVKBtZsHbjkQxkIhg1aJZ7x6keLPBoOLxwIw2U3rLPCsEYBLrfBr9pe8NrTGw+/eDycMM4b+zHIT5SOYKH01G4zxZK2R9SgmqAyU/YOhBCCDIXTtLYPkfqLuQfvH2dHyZdbKnF6qYWiz+qu0nknVXN5HIFVuxiDuvUgXTUnOhHBlvNw7Mlw66AKxJ4eZo2MLw3wPP7vKMUjUdUXzDdXulRKRlPKE/rQWa0iUq2T8Tk1YYBlqPWkFK1MAeU0qTX6hzOTQFMnZBk1YT1SFxDfqeDzD/G9WIHG6m3KTN3gOsn+4gRx+qgW2whCft+E1QMn8TA3L/13lAgoGlgeWF9uwt6oyrMVG73sJ4A8/h+1SbzdxvYDrybQy8TTgre40ftdJGBVVj7qBvE6W6imyzXXlMFBY1TCAFlVygENLQx6PUP8Dv2vvYlcOVTAbp/n0XO1ZHsLp95LiVW1k6QFf5OfMyJ2NjZegorBPFX8yMfz+ioWnSYze3M=
  file_glob: true
  file: dist/announce-new-channel-*.tar.gz
  skip_cleanup: true
  on:
    repo: kaakaa/mmplugin-announce-new-channel
    tags: true
