defaults: &defaults
  working_directory: /go/src/github.com/kaakaa/mmplugin-announce-new-channel

version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make check-style

  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make test
  
  publish-github-release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: make dist
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJEECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ${CIRCLE_TAG} ./dist/org.kaakaa.mmplugin-channel-recommender-${CIRCLE_TAG}.tar.gz

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - lint
      - test
      - publish-github-release:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v\d+\.\d+\.\d+$/
